name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: Test on Go ${{ matrix.go-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.17', '1.18', '1.19', '1.20', '1.21', '1.22', '1.23']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install dependencies
      run: go get -v ./...

    - name: Check go fmt
      run: |
        res=$(gofmt -s -l .)
        if [ -n "$res" ]; then
          echo "::error ::Code is not formatted with go fmt -s"
          echo $res
          exit 1
        fi

    - name: Run tests
      run: go test -v ./...
